dbt_docker:
  outputs:
    dev:
      dbname: postgres_docker_db
      host: postgres_docker
      keepalives_idle: 0
      password: postgres_docker_password
      port: 5432
      schema: public
      threads: 4
      type: postgres
      user: postgres_docker_user
  target: dev
insurance_data_platform:
  outputs:
    dev:
      dbname: insurance_platform
      host: postgres_docker
      pass: postgres_docker_password
      port: 5432
      schema: analytics
      threads: 4
      type: postgres
      user: postgres_docker_user
  target: dev
