name: postgres_exporter_docker

services:
  postgres_exporter_docker:
    image: prometheuscommunity/postgres-exporter:v0.17.1
    container_name: postgres_exporter_docker

    env_file:
      - .env

    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable"

    ports:
      - "${POSTGRES_EXPORTER_PORT}:9187"

    restart: unless-stopped

    networks:
      - default

networks:
  default:
    external: true
    name: dockerlab_network