name: spark_docker

services:

  spark-master:
    image: bitnami/spark:3.5.5

    container_name: spark_master_docker

    hostname: spark-master

    environment:
      SPARK_MODE: master
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8080

    ports:
      - "${SPARK_MASTER_PORT}:7077"
      - "${SPARK_MASTER_UI_PORT}:8080"

    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ./jars:/opt/bitnami/spark/jars
      - ./data:/opt/bitnami/spark/data
      - ./logs:/opt/bitnami/spark/logs

    restart: unless-stopped

    networks:
      - default

  spark-worker-1:
    image: bitnami/spark:3.5

    container_name: spark_worker1_docker

    hostname: spark-worker-1

    depends_on:
      - spark-master

    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: ${SPARK_WORKER_MEMORY}
      SPARK_WORKER_CORES: ${SPARK_WORKER_CORES}

    ports:
      - "${SPARK_WORKER1_UI_PORT}:8081"

    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ./jars:/opt/bitnami/spark/jars
      - ./data:/opt/bitnami/spark/data
      - ./logs:/opt/bitnami/spark/logs

    restart: unless-stopped

    networks:
      - default

  spark-worker-2:
    image: bitnami/spark:3.5

    container_name: spark_worker2_docker

    hostname: spark-worker-2

    depends_on:
      - spark-master

    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: ${SPARK_WORKER_MEMORY}
      SPARK_WORKER_CORES: ${SPARK_WORKER_CORES}

    ports:
      - "${SPARK_WORKER2_UI_PORT}:8081"

    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ./jars:/opt/bitnami/spark/jars
      - ./data:/opt/bitnami/spark/data
      - ./logs:/opt/bitnami/spark/logs

    restart: unless-stopped

    networks:
      - default

networks:
  default:
    external: true
    name: dockerlab_network