name: spark_docker

services:

  spark-master:
    image: apache/spark:${SPARK_VERSION}
    container_name: spark_master_docker

    hostname: spark-master

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.master.Master

    environment:
      SPARK_NO_DAEMONIZE: "true"
      SPARK_MASTER_HOST: ${SPARK_MASTER_HOST}
      TZ: ${TZ}

    ports:
      - "${SPARK_MASTER_PORT}:7077"
      - "${SPARK_MASTER_WEBUI_PORT}:8080"

    volumes:
      - ./jobs:/opt/spark/jobs
      - ./jars:/opt/spark/jars
      - ./data:/opt/spark/data
      - ./logs:/opt/spark/logs
      - ./notebooks:/opt/spark/notebooks

    restart: unless-stopped

    networks:
      - default

networks:
  default:
    external: true
    name: dockerlab_network